import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'

//Components
import Navbar from '../components/Navbar'
import Button from '../components/Button'
import Modal from '../components/Modal'

//Images
import graphic from '../assets/Graphic.svg'

const StyledMain = styled.main`
  width: 100%;
  height: 100vh;
  background-image: url('/BgGradient.svg');
  background-repeat: no-repeat;
  background-size: cover;
`

const Peaks = styled.div`
  aspect-ratio: 6/1;
  width: 100%;
  background-repeat: no-repeat;
  background-position: center;
  background-size: cover;
  background-image: url('/Frame.svg');
`

const Hero = styled.div`
  width: 100%;
  min-height: 75vh;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  padding: 0 2em 2em 2em;
  margin-top: -1em;
  @media(min-height: 735px) {
    justify-content: space-around;
  }
  @media(min-width: 650px) {
    flex-direction: row-reverse;
    justify-content: center;
    padding: 0 10%;
  }
`

const HeroImg = styled.div`
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: flex-start;
  @media(min-width: 650px) {
    width: 50%;
  }
`

const HeroText = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  text-align: center;
  @media(min-width: 650px) {
    height: 100%;
    width: 50%;
    justify-content: space-between;
    align-items: flex-start;
    text-align: start;
  }
`

const Title = styled.h1`
  font-size: 25px;
  font-weight: 400;
  color: #c6c3ff;
  margin: 0;
  @media(min-height: 700px) {
    font-size: 30px;
  }
  @media(min-width: 750px) {
    font-size: 40px;
  }
  @media(min-width: 1000px) {
    font-size: 50px;
  }
  @media(min-width: 1400px) {
    font-size: 60px;
  }
`

const Description = styled.p`
  color: #AEABFF;
  margin-bottom: 2em;
  @media(min-width: 650px) {
    width: 75%;
  }
`

const Details = styled.div`
  width: 100%;
  height: 100vh;
  background-color: #172B37;
  margin-top: -4px;
`



export default function Home() {
  return (
    <StyledMain>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Hero>
        <HeroImg>
          <Image className="graphic" src={graphic} alt="hero image"/>
        </HeroImg>
          <HeroText>
          <Title>Modernize your<br/>issue tracking.</Title>
          <Description>
            BugStompr is a team-based bug tracker for easily creating and managing issue tickets on a project dashboard.<br/><br/>
            Time is money, track and update any and all bugs in your codebase for faster, more seamless production.
          </Description>
          <Modal toggler={<Button text="Sign Up For Free >"/>}/>
        </HeroText>
      </Hero>
      <Peaks></Peaks>
      <Details>
      
      </Details>

    </StyledMain>
  )
}
