import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'

import logo from '../assets/Logo.svg'

import burger from '../assets/BurgerMenu.svg'
import graphic from '../assets/Graphic.svg'

const StyledMain = styled.main`
  width: 100%;
  height: 100vh;
  background-image: url('/BgGradient.svg');
  background-repeat: no-repeat;
  background-size: cover;
`

const StyledNav = styled.nav`
  width: 100%;
  height: auto;
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0 2em;
  padding-top: 2em;
`

const Links = styled.div`
  display: none;
  @media(min-width: 1000px) {
    display: flex;
    width: 15em;
    justify-content: space-between;
  }
`

const Peaks = styled.div`
  aspect-ratio: 6/1;
  width: 100%;
  background-repeat: no-repeat;
  background-position: center;
  background-size: cover;
  background-image: url('/Frame.svg');
`

const Burger = styled.div`
  @media(min-width: 1000px) {
    display: none;
  }
`

const Hero = styled.div`
  width: 100%;
  height: 75vh;
  display: flex;
  flex-direction: column;
  justify-content: center;
  padding: 0 2em;
`

const HeroImg = styled.div`
  width: 100%;
  height: auto;
  display: flex;
  justify-content: center;
  align-items: center;
  margin-bottom: -2em;
  @media(min-height: 320px) {
    margin-top: -6em;
    .graphic {
      width: 75%;
    }
  }
`

const Title = styled.h1`
  font-size: 35px;
  font-weight: 300;
  color: #c6c3ff;
  text-align: center;
`

const Description = styled.p`
  color: #AEABFF;
  text-align: center;
`

const Details = styled.div`
  width: 100%;
  height: 100vh;
  background-color: #172B37;
  margin-top: -4px;
`

export default function Home() {
  return (
    <StyledMain>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledNav>
        <Image src={logo} width={200} height={75} alt="logo"/>
        <Burger>
          <Image src={burger} width={50} height={50} alt="burger menu"/>
        </Burger>
        <Links>
          <p>Sign Up</p>
          <p>Sign In</p>
          <p>Guest</p>
        </Links>
      </StyledNav>
      <Hero>
        <HeroImg>
          <Image className="graphic" src={graphic} alt="hero image"/>
        </HeroImg>
        <Title>Modernize your<br/>issue tracking.</Title>
        <Description>
          BugStompr is a team-based bug tracker for easily creating and managing issue tickets on a project dashboard.<br/><br/>
          Time is money, track and update any and all bugs in your codebase for faster, more seamless production.
        </Description>
      </Hero>
      <Peaks></Peaks>
      <Details>
      
      </Details>

    </StyledMain>
  )
}
